# Generated by Django 2.1.2 on 2018-12-23 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailstaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_manager', models.EmailField(max_length=254, verbose_name='Email менеджера:')),
                ('user_manager', models.ForeignKey(blank=True, help_text='Може бути не вказаний!', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач (User) якому належить Email адрес')),
            ],
            options={
                'verbose_name': 'Email менеджера',
                'verbose_name_plural': 'Emails менеджера',
            },
        ),
        migrations.CreateModel(
            name='Emailwebservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_use_tls', models.CharField(choices=[(True, 'True'), (False, 'False')], default='True', max_length=5, verbose_name='EMAIL_USE_TLS')),
                ('email_host', models.CharField(max_length=64, verbose_name='EMAIL_HOST')),
                ('email_port', models.DecimalField(decimal_places=5, max_digits=5, verbose_name='EMAIL_PORT')),
                ('email_host_user', models.CharField(max_length=64, verbose_name='EMAIL_HOST_USER')),
                ('email_host_password', models.CharField(max_length=64, verbose_name='пароль')),
                ('default_from_email', models.CharField(blank=True, max_length=64, null=True, verbose_name='DEFAULT_FROM_EMAIL')),
                ('default_to_email', models.CharField(blank=True, max_length=64, null=True, verbose_name='DEFAULT_TO_EMAIL')),
            ],
            options={
                'verbose_name': 'Параметри поштового клієнта',
                'verbose_name_plural': 'Параметри поштового клієнта',
            },
        ),
        migrations.CreateModel(
            name='Phonestaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_manager', models.EmailField(max_length=254, verbose_name='Телефонний номер менеджера:')),
                ('user_manager', models.ForeignKey(blank=True, help_text='Може бути не вказаний!', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач (User) якому належить телефонний')),
            ],
            options={
                'verbose_name': 'Телефонний номер менеджера',
                'verbose_name_plural': 'Телефонний номер менеджера',
            },
        ),
        migrations.CreateModel(
            name='Systemoptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_send', models.BooleanField(blank=True, default=True, help_text='Якщо відміченно, то на всі Email адреси, що переліченні нижче будуть вілісланні електронні листи з інформацією про заказ', null=True, verbose_name='Розсилати електронні листи при отриманні заказу?')),
                ('phone_send', models.BooleanField(blank=True, default=True, help_text='Якщо відміченно, то на всі телефонні номери, що переліченні нижче будуть вілісланні СМС про новий заказУВАГА! По СМС неможливо відправити повну інформацію про заказ: тому рекомендується використовувавти в парі з Email інформуванням', null=True, verbose_name='Розсилати СМС при отриманні заказу(послуга платна)?')),
                ('email_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systemoptions.Emailwebservice', verbose_name='Email з якого надходитимуть електронні листи інформування')),
                ('emails_pool', models.ManyToManyField(blank=True, db_index=True, to='systemoptions.Emailstaff', verbose_name='Перелік електронних адресів (Emails)')),
                ('phones_pool', models.ManyToManyField(blank=True, db_index=True, to='systemoptions.Phonestaff', verbose_name='Перелік телефонних номерів')),
            ],
            options={
                'verbose_name': 'Службові опції',
                'verbose_name_plural': 'Службові опції',
            },
        ),
    ]
