# Generated by Django 2.1.2 on 2018-12-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemoptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailwebservice',
            name='email_port',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='EMAIL_PORT'),
        ),
        migrations.AlterField(
            model_name='phonestaff',
            name='phone_manager',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Телефонний номер менеджера:'),
        ),
        migrations.AlterField(
            model_name='systemoptions',
            name='email_send',
            field=models.BooleanField(blank=True, default=True, help_text='Якщо відміченно, то на всі Email адреси, що виділенні нижче будуть вілісланні електронні листи з інформацією про заказ', null=True, verbose_name='Розсилати електронні листи при отриманні заказу?'),
        ),
        migrations.AlterField(
            model_name='systemoptions',
            name='phone_send',
            field=models.BooleanField(blank=True, default=True, help_text='Якщо відміченно, то на всі телефонні номери, що виділенні нижче будуть вілісланні СМС про новий заказУВАГА! По СМС неможливо відправити повну інформацію про заказ: тому рекомендується використовувавти в парі з Email інформуванням', null=True, verbose_name='Розсилати СМС при отриманні заказу(послуга платна)?'),
        ),
    ]
