# Generated by Django 2.1.2 on 2018-12-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemoptions', '0004_auto_20181223_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailwebservice',
            name='email_host_password',
            field=models.CharField(max_length=64, verbose_name='EMAIL_HOST_PASSWORD'),
        ),
    ]
