# Generated by Django 2.1.2 on 2018-12-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemoptions', '0005_auto_20181223_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailwebservice',
            name='email_port',
            field=models.PositiveSmallIntegerField(verbose_name='EMAIL_PORT'),
        ),
        migrations.AlterField(
            model_name='systemoptions',
            name='email_send',
            field=models.BooleanField(blank=True, default=True, help_text='Якщо відміченно, то на всі Email адреси, що виділенні нижче будуть вілісланні електронні листи з інформацією про заказ', null=True, verbose_name="Розсилати email'и при отриманні заказу?"),
        ),
    ]
