# Generated by Django 2.1.2 on 2018-12-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemoptions', '0008_auto_20181223_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailwebservice',
            name='email_use_tls',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=True, max_length=5, verbose_name='EMAIL_USE_TLS'),
        ),
    ]
