# Generated by Django 2.1.2 on 2018-12-26 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemoptions', '0017_auto_20181226_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonestaff',
            name='phone_manager',
            field=models.CharField(help_text='Формат для телефонного номера: 0XXXXXXXXX (напр.: 0982548248)', max_length=10, validators=[django.core.validators.RegexValidator(message='Номер телефону може складатися лише з цифр!.', regex='^\\d{10}$')], verbose_name='Телефонний номер менеджера:'),
        ),
    ]
