# Generated by Django 2.1.2 on 2018-11-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20181124_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='r_commit',
            field=models.TextField(blank=True, help_text='Ваш коментар', max_length=1024, null=True, verbose_name='Відгук / коментар'),
        ),
    ]
