# Generated by Django 2.1.2 on 2018-11-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20181125_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dates_commit',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='r_commit',
            field=models.TextField(blank=True, db_index=True, help_text='Ваш коментар', max_length=1024, null=True, verbose_name='Відгук / коментар'),
        ),
    ]
