# Generated by Django 2.1.2 on 2018-10-11 08:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(blank=True, help_text='* Як до Вас звертатись(Імя, Фамілія)', max_length=128, null=True, verbose_name='Реальне імя')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='client_photo', verbose_name='Фото')),
                ('phone', models.CharField(help_text='* Номер телефону', max_length=28, verbose_name='Номер телефону')),
                ('discount_client', models.IntegerField(blank=True, default=0, help_text='Увага: персональна знижка сумується зі знижкою продукту. Можливі значення: 0 - 50', null=True, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)], verbose_name='Персональна знижка, %')),
                ('dates_reg', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата реєстрації')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
            },
        ),
    ]
