# Generated by Django 2.1.2 on 2018-10-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Дата народження', null=True, verbose_name='Дата народження'),
        ),
        migrations.AddField(
            model_name='client',
            name='location',
            field=models.CharField(blank=True, help_text='Адреса доставки/проживання', max_length=256, null=True, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='client',
            name='real_name',
            field=models.CharField(blank=True, help_text='Як до Вас звертатись(Імя, Фамілія)', max_length=128, null=True, verbose_name='Реальне імя'),
        ),
    ]
