# Generated by Django 2.1.2 on 2018-10-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181011_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='e_mail',
            field=models.EmailField(blank=True, help_text='* Електронна пошта', max_length=128, null=True),
        ),
    ]
