# Generated by Django 2.1.2 on 2018-10-11 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_client_e_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='e_mail',
            field=models.EmailField(blank=True, help_text='Електронна пошта', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, help_text='Номер телефону', max_length=28, null=True, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
