# Generated by Django 2.1.2 on 2018-10-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181011_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, help_text='Номер телефону', max_length=28, null=True, unique=True, verbose_name='Номер телефону'),
        ),
    ]
