# Generated by Django 2.1.2 on 2018-10-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181012_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='e_mail',
        ),
    ]
