# Generated by Django 2.1.2 on 2018-11-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181112_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dates_reg',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, db_index=True, help_text='Номер телефону', max_length=28, null=True, unique=True, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='client',
            name='real_name',
            field=models.CharField(blank=True, db_index=True, help_text='Як до Вас звертатись(Імя, Фамілія)', max_length=128, null=True, verbose_name='Реальне імя'),
        ),
    ]
