# Generated by Django 2.1.2 on 2018-11-28 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20181127_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, db_index=True, help_text='Якщо не вказувати, по замовчуванню: це місто', max_length=128, null=True, verbose_name='Місто')),
                ('street', models.CharField(db_index=True, help_text='Назва вулиці', max_length=128, verbose_name='Вулиця')),
                ('building', models.CharField(blank=True, db_index=True, help_text='Номер будинку', max_length=6, null=True, verbose_name='Будинок')),
                ('apartment', models.CharField(blank=True, db_index=True, help_text='Номер квартири (якщо є)', max_length=6, null=True, verbose_name='Квартири')),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='location',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Адреса доставки/проживання', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Addresses', verbose_name='Адреса'),
        ),
    ]
