# Generated by Django 2.1.2 on 2018-12-11 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20181128_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_city', models.CharField(blank=True, db_index=True, default='Тернопіль', help_text='Якщо не вказувати, по замовчуванню: це місто', max_length=128, null=True, verbose_name='Назва міста')),
            ],
        ),
        migrations.CreateModel(
            name='Streets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_street', models.CharField(db_index=True, help_text='Назва вулиці', max_length=128, verbose_name='Вулиця')),
                ('city', models.ForeignKey(help_text='Якщо не вказувати, по замовчуванню: це місто', on_delete=django.db.models.deletion.CASCADE, to='main.Cities', verbose_name='Місто')),
            ],
        ),
        migrations.AlterModelOptions(
            name='addresses',
            options={'verbose_name': 'Адреса', 'verbose_name_plural': 'Адреси'},
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='city',
        ),
        migrations.AlterField(
            model_name='addresses',
            name='apartment',
            field=models.CharField(blank=True, db_index=True, help_text='Номер квартири (якщо є)', max_length=6, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='street',
            field=models.ForeignKey(help_text='Назва вулиці', max_length=128, on_delete=django.db.models.deletion.CASCADE, to='main.Streets', verbose_name='Вулиця'),
        ),
    ]
