# Generated by Django 2.1.2 on 2018-12-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20181211_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'Місто', 'verbose_name_plural': 'Міста'},
        ),
        migrations.AlterModelOptions(
            name='streets',
            options={'verbose_name': 'Вулиця', 'verbose_name_plural': 'Вулиці'},
        ),
    ]
