# Generated by Django 2.1.2 on 2018-12-11 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='town',
            field=models.ForeignKey(default=1, help_text='Якщо не вказувати, по замовчуванню: це місто', on_delete=django.db.models.deletion.CASCADE, to='main.Cities', verbose_name='Місто'),
            preserve_default=False,
        ),
    ]
