# Generated by Django 2.1.2 on 2018-11-08 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='date_of_readiness',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='На коли має бути готоаий заказ: дата і час', verbose_name='Готовність на(дата):'),
        ),
    ]
