# Generated by Django 2.1.2 on 2018-11-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20181108_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='state_of_status',
            field=models.CharField(choices=[('new', 'новий'), ('executed', 'виконаний')], default='new', max_length=10, verbose_name='Статус заказу'),
        ),
    ]
