# Generated by Django 2.1.2 on 2018-11-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_basket_state_of_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='state_of_status',
            field=models.CharField(choices=[('new', 'новий'), ('executed', 'виконаний')], default='new', max_length=10, verbose_name='Статус кошика'),
        ),
    ]
