# Generated by Django 2.1.2 on 2018-11-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20181124_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dates_order',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата оформлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=128, null=True, verbose_name='Ключ сесії(служова інформація)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='update_order',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
