# Generated by Django 2.1.2 on 2018-11-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20181127_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_of_order',
            field=models.CharField(choices=[('new', 'новий'), ('executed', 'виконаний')], default='new', max_length=10, verbose_name='Статус заказу'),
        ),
    ]
