# Generated by Django 2.1.2 on 2018-12-09 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_status_of_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basket_of_client', to='main.Client', verbose_name='Клієнт'),
        ),
    ]
