# Generated by Django 2.1.2 on 2018-12-09 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_remove_product_is_stuffing_id'),
        ('orders', '0010_basket_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='is_stuffing_product',
            field=models.ForeignKey(blank=True, help_text='Службове поле.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product', verbose_name='Начинка/серединка, якщо є'),
        ),
    ]
