# Generated by Django 2.1.2 on 2018-12-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_basket_is_stuffing_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='is_stuffing_product',
        ),
        migrations.AddField(
            model_name='order',
            name='is_stuffing_id',
            field=models.IntegerField(blank=True, help_text='Службове поле.', null=True, verbose_name='Начинка/серединка, якщо є'),
        ),
    ]
