# Generated by Django 2.1.2 on 2018-12-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20181209_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Всі знижки враховані', max_digits=10, verbose_name='Вартість кошика'),
        ),
    ]
