# Generated by Django 2.1.1 on 2018-09-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='commits_from_product', to='blogs.Comment', verbose_name='Коментарі / відгуки'),
        ),
    ]
