# Generated by Django 2.1.1 on 2018-09-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180925_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug_category',
            field=models.SlugField(blank=True, editable=False, max_length=128, null=True, unique=True),
        ),
    ]
