# Generated by Django 2.1.1 on 2018-09-26 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180925_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_plus_type_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_product_of_type', to='products.Type', verbose_name='Категорія+Тип'),
        ),
    ]
