# Generated by Django 2.1.1 on 2018-09-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180926_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='price_type',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, help_text='Вираховується автоматично', max_digits=7, null=True, verbose_name='Мінімальна ціна одиниці цього типу'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Вартість за кг. чи за шт.', max_digits=7, verbose_name='Ціна за одиницю'),
        ),
    ]
