# Generated by Django 2.1.1 on 2018-09-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180926_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='price_type',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Вираховується автоматично', max_digits=7, null=True, verbose_name='Мінімальна ціна одиниці цього типу'),
        ),
    ]
