# Generated by Django 2.1.1 on 2018-09-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180926_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='price_type',
        ),
    ]
