# Generated by Django 2.1.1 on 2018-09-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180927_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='slide_photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='main_photo',
            field=models.BooleanField(default=True, help_text='Головне фото, яке відображається в каталогах. Вимоги: співвідношення сторін 2:3, інакше зображення буде обрізано!', verbose_name='Слайди'),
        ),
    ]
