# Generated by Django 2.1.1 on 2018-09-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20180930_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='main_photo',
            field=models.BooleanField(default=True, help_text='Головне фото, яке відображається в каталогах. Вимоги: співвідношення сторін 2:3, інакше зображення буде обрізано!', verbose_name='Головне/каталожне'),
        ),
    ]
