# Generated by Django 2.1.1 on 2018-10-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20180930_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='disclaimer',
            field=models.CharField(blank=True, help_text='Застереження для категорії, відображатиметься на сайті, коли активувати', max_length=128, null=True, verbose_name='Текст застереження'),
        ),
        migrations.AddField(
            model_name='category',
            name='disclaimer_is_visible',
            field=models.BooleanField(default=False, help_text='Застереження для категорії, відображатиметься на сайті, коли активувати', verbose_name='Застереження показувати/не показувати'),
        ),
    ]
