# Generated by Django 2.1.1 on 2018-10-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20181002_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='disclaimer',
            field=models.TextField(blank=True, help_text='Застереження для категорії, відображатиметься на сайті, коли активувати', max_length=128, null=True, verbose_name='Текст застереження'),
        ),
    ]
