# Generated by Django 2.1.1 on 2018-10-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20181002_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug_category',
            field=models.SlugField(blank=True, editable=False, max_length=256, null=True, unique=True),
        ),
    ]
