# Generated by Django 2.1.1 on 2018-10-05 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20181002_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='direction',
            field=models.IntegerField(default=1, help_text='Порядок показу категорії: менше значить вище', validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)], verbose_name='Пріорітет показу категорії'),
            preserve_default=False,
        ),
    ]
