# Generated by Django 2.1.2 on 2018-11-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20181108_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(help_text='Категорія продукту. Наприклад: Торти, Фігурки, Зефір і т. д.', max_length=25, verbose_name='Категорія продукту'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='Назва'),
        ),
    ]
