# Generated by Django 2.1.2 on 2018-11-28 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20181127_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.IntegerField(blank=True, help_text='Рейтинг продукту: відображається зірочками, вираховується автоматично на основі оцінки у відгуках', null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Рейтинг продукту'),
        ),
        migrations.AddField(
            model_name='product',
            name='cooking_time',
            field=models.TimeField(blank=True, help_text='Час виготовлення в годинах (макс. значення 24 год). Величина приблизна і використовується для розрахунку терміну приблизного виконання замовлення', null=True, verbose_name='Час виготовлення в годинах'),
        ),
    ]
