# Generated by Django 2.1.2 on 2018-11-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20181128_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cooking_time',
            field=models.DurationField(blank=True, help_text='Час виготовлення в годинах (макс. значення 24 год). Величина приблизна і використовується для розрахунку терміну приблизного виконання замовлення', null=True, verbose_name='Час виготовлення в годинах'),
        ),
    ]
