# Generated by Django 2.1.2 on 2018-11-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20181128_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cooking_time',
            field=models.DurationField(blank=True, help_text='Час виготовлення. Величина приблизна і використовується для розрахунку терміну приблизного виконання замовлення', null=True, verbose_name='Час виготовлення'),
        ),
    ]
