# Generated by Django 2.1.2 on 2018-12-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_remove_product_is_stuff_plus'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Товари з цієї категорії не можно замовити окремо, лише з основними товарами. Проте вони доступні для перегляду', verbose_name='Супутня категорія'),
        ),
    ]
