# Generated by Django 2.1.2 on 2018-12-08 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_category_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='direction',
            field=models.IntegerField(help_text='Порядок показу категорії: менше значить вище', unique=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)], verbose_name='Пріорітет показу'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, help_text='Опис продукту, який відображатиметься на сайті.', max_length=255, null=True, verbose_name='Опис продукту'),
        ),
    ]
