# Generated by Django 2.1.2 on 2018-12-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20181208_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_stuffing_id',
            field=models.IntegerField(blank=True, help_text='Службове поле.', null=True, verbose_name='ID начинки/серединки, якщо є'),
        ),
    ]
