# Generated by Django 2.1.2 on 2018-12-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_product_is_stuffing_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_stuffing_id',
        ),
    ]
