# Generated by Django 2.1.2 on 2018-12-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_remove_product_is_stuffing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='accessibility',
            field=models.BooleanField(default=True, help_text='Виняток: кат: Достаква. Повинна бути не доступна(знята галочка)!!!', verbose_name='Доступність'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, db_index=True, help_text='Забороняється використовувати символ "+" в назві продукту!', max_length=128, null=True, verbose_name='Назва'),
        ),
    ]
