# Generated by Django 2.1.2 on 2019-01-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20181227_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, db_index=True, help_text='Символи "+" будуть замінені на "-"!', max_length=128, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='type',
            name='category_plus_type',
            field=models.CharField(blank=True, editable=False, help_text='Генерується автоматично!', max_length=50, null=True, verbose_name='Категорія+Тип продукту:'),
        ),
    ]
