# Generated by Django 2.1.2 on 2019-01-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_auto_20190102_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='direction',
            new_name='direction_cat',
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(help_text='Прийаються файли(фото) лише у фораматі JPEG!', null=True, upload_to='products_photo', verbose_name='Фото продукту'),
        ),
    ]
