# Generated by Django 2.1.2 on 2019-01-28 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20190107_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, help_text='Опис продукту, який відображатиметься на сайті.', max_length=512, null=True, verbose_name='Опис продукту'),
        ),
        migrations.AlterField(
            model_name='type',
            name='direction_type',
            field=models.IntegerField(help_text='Порядок показу типу(загальний: для всіх типів): менше значить вище', unique=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)], verbose_name='Пріорітет показу'),
        ),
    ]
