# Generated by Django 2.1.2 on 2019-01-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20190128_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, help_text='Опис продукту, який відображатиметься на сайті. Макс.: 512 символів.', max_length=512, null=True, verbose_name='Опис продукту'),
        ),
    ]
