# Generated by Django 2.1.2 on 2019-02-15 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_auto_20190215_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='step_for_min_quantity',
            field=models.FloatField(blank=True, default=0.1, help_text='Рекомендації: 0.1 для вагових продуктів та 1 для продуктів, що продаються поштучно. Значення по замовчуванню (якщо не вказати): 0.1', null=True, verbose_name='Крок збільшення/зменшення для кількості'),
        ),
        migrations.AlterField(
            model_name='type',
            name='min_quantity',
            field=models.IntegerField(blank=True, default=1, help_text='Мінімальна кількість шт чи кг, яку можна замовити. Вказується для типу продуктів в цілому. Значення по замовчуванню(якщо не вказати): 1', null=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)], verbose_name='Мінімально можлива кількість до замовлення:'),
        ),
    ]
